######## Set this as appropriate for the project. ########

filter:
    paths:
        - src/*
        - tests/*
    dependency_paths:
        - application/vendor/*
    excluded_paths:
        - application/vendor/*
        - application/console/runtime/*

########### [End of project-specific section] ############
tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2