language: php
php: 5.6
before_script:
    - composer install
    - mysql -e 'CREATE DATABASE `vergo_base`;'
    - mysql -e 'USE mysql; UPDATE user SET password=PASSWORD('123') WHERE user='root'; FLUSH PRIVILEGES;'

env:
    - DB=mysql

script:
    - sh run_tests.sh