app:
    resource: "@AppBundle/Controller/"
    type:     annotation

vergo:
    resource: "@AppBundle/Resources/config/routing.yml"

naissance:
    resource: "@NaissanceBundle/Resources/config/routing.yml"