admin_index:
    path:     /
    defaults: { _controller: AppBundle:Admin:index }

admin_login:
    path:     /login
    defaults: { _controller: AppBundle:Admin:login }
    methods: [GET]

admin_login_check:
    path:     /login
    defaults: { _controller: AppBundle:Admin:loginCheck }
    methods: [POST]