index:
    path:     /vadmin
    defaults: { _controller: AppBundle:Admin:index }

login:
    path:     /login
    defaults: { _controller: AppBundle:Admin:login }

vergo_api:
    prefix: /api
    resource: '@AppBundle/Resources/config/routing_api.yml'