admin_index:
    path:     /
    defaults: { _controller: AppBundle:Admin\Base:index }

admin_login:
    path:     /login
    defaults: { _controller: AppBundle:Admin\Base:login }
    methods: [GET]

admin_login_check:
    path:     /login
    defaults: { _controller: AppBundle:Admin\Base:loginCheck }
    methods: [POST]

admin_article_index:
    path: /articles
    defaults: { _controller: AppBundle:Admin\Article:index }
    methods: [GET]