services:
    fos_user.doctrine_registry:
        alias: doctrine

    rqs.database.tester:
        class: 'AppBundle\Service\DatabaseTesterService'
        arguments:
            - '@doctrine'

    v.auth:
        class: 'AppBundle\Service\AuthService'
        calls:
           - [setContainer, ['@service_container']]