AppBundle\Entity\Article:
    type: entity
    table: articles
    repositoryClass: AppBundle\Repository\ArticleRepository

    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY

    manyToOne:
        user:
            targetEntity: AppBundle\Entity\SUser
            inversedBy: articles
            fetch: EXTRA_LAZY
            joinColumn:
                name: user_id
                referencedColumnName: id

    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: title
        text:
            type: string
            nullable: false
            fixed: false
            column: text
        status:
            type: integer
            nullable: false
            unsigned: true
            column: status
        viewCount:
            type: integer
            nullable: false
            unsigned: true
            column: view_count
        created:
            type: datetime
            nullable: false
            column: created
        updated:
            type: datetime
            nullable: false
            column: updated
