AppBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: AppBundle\Repository\UserRepository

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY

    oneToMany:
        articles:
            targetEntity: LB\AppBundle\Entity\Articles
            mappedBy: user
            fetch: EXTRA_LAZY

    fields:
        updated:
            type: datetime
            nullable: false
